// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//  * Imports
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

import 'package:flutter/material.dart';

// Pub Dev Imports
// ! At present, this module is plain UI. Needs integration with firebase

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//  * Formfield UI
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
class NewHealthCard extends StatelessWidget {
  const NewHealthCard({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        toolbarHeight: 100,
        title: Text('Add Health Card'),
      ),
      body: Padding(
        padding: EdgeInsets.fromLTRB(20, 0, 20, 0),
        child: _FormField(),
      ),
    );
  }
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//  * Stateful Health Form
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
class _FormField extends StatefulWidget {
  _FormField({Key key}) : super(key: key);

  @override
  __FormFieldState createState() => __FormFieldState();
}

class __FormFieldState extends State<_FormField> {
  // Controllers
  var name = TextEditingController();
  var issueDate = TextEditingController();
  var cardNum = TextEditingController();
  var cvv = TextEditingController();
  var now = DateTime.now();
  bool isValidated = false;

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: <Widget>[
        SizedBox(
          height: 32,
        ),
        TextFormField(
          controller: name,
          decoration: InputDecoration(
              border: OutlineInputBorder(),
              icon: Icon(Icons.person),
              hintText: 'First Last',
              labelText: 'Name'),
        ),
        SizedBox(
          height: 32,
        ),
        TextFormField(
          controller: cardNum,
          keyboardType: TextInputType.number,
          decoration: InputDecoration(
              border: OutlineInputBorder(),
              icon: Icon(Icons.calendar_view_day_sharp),
              hintText: 'xxxx xxxx xxxx xxxx',
              // TODO: import pub dev module to give autospace
              labelText: 'Aadhar Card Number'),
        ),
        SizedBox(
          height: 32,
        ),
        TextFormField(
          controller: cvv,
          keyboardType: TextInputType.number,
          decoration: InputDecoration(
              border: OutlineInputBorder(),
              icon: Icon(Icons.lock_outline_rounded),
              hintText: '****',
              labelText: 'Security Key'),
        ),
        SizedBox(
          height: 32,
        ),
        TextFormField(
          controller: issueDate..text = '${now.year}-${now.month}-${now.day}',
          // TODO: add better formatting for ${now} = Jan DD, YYYY
          enabled: false,
          decoration: InputDecoration(
              border: OutlineInputBorder(),
              icon: Icon(Icons.date_range_outlined),
              labelText: 'Issue Date (Autogenerated)'),
        ),
        SizedBox(
          height: 32,
        ),
        ElevatedButton.icon(
          onPressed: () {
            print('Validate Pressed');
            isValidated = true;
            if (true) {
              HealthCardData user = new HealthCardData(
                  name.text, issueDate.text, cardNum.text, cvv.text);
              print(user.printDetails());
            }
            setState(() {});
            //TODO: Implement validator
          },
          icon: Icon(Icons.verified_user_sharp, size: 36),
          label: Text(
            'Validate',
            style: TextStyle(fontSize: 20),
          ),
          style: ElevatedButton.styleFrom(
            primary: Colors.green,
            elevation: 10,
            padding: EdgeInsets.symmetric(horizontal: 0, vertical: 20),
          ),
        ),
        SizedBox(
          height: 32,
        ),
        ElevatedButton.icon(
          onPressed: _isValidated(),
          icon: Icon(Icons.cloud_upload_rounded, size: 36),
          label: Text(
            'Submit',
            style: TextStyle(fontSize: 20),
          ),
          style: ElevatedButton.styleFrom(
            primary: Colors.green,
            elevation: 10,
            padding: EdgeInsets.symmetric(horizontal: 0, vertical: 20),
          ),
        ),
      ],
    );
  }

  Function _isValidated() {
    if (isValidated) {
      return () {
        print('Pushing to firebase...');
        //TODO: Add firebase push here}
      };
    } else {
      return null;
    }
  }
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//  * Health Form Constructor Class
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
class HealthCardData {
  HealthCardData(this.name, this.issueDate, this.cardNum, this.cvv);
  String name;
  String issueDate;
  String cardNum;
  String cvv;

  String printDetails() {
    return 'Name: $name\nIssue Date: $issueDate\nCard Number: $cardNum\nCVV: $cvv';
  }
}
